### ISSUE TITLE
please refer to the hplib repo

### ISSUE THREAD

**Issue by ttjaden** [missing-user/heat-pump-dashboard#5]
Seems like you are using the hplib? Would be great to refer to the repo 
https://github.com/FZJ-IEK3-VSA/hplib

For reference purposes:

Citation: Tjarko Tjaden, Hauke Hoops, Kai Rösken. (2021). RE-Lab-Projects/hplib: heat pump library (v2.0). Zenodo. https://doi.org/10.5281/zenodo.5521597

**Comment by missing-user** [comment]
Thanks for the notification, I added a citation for both to the sources. It was cited in my report for university, but apparently some sources got lost when generating the readme.

P.S.: the version available as `pip install` had some issues with paths to the hplib database under Linux, so it wasn't usable without modification for us.
